# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: mido
subtitle: mido's blog about dev and design
author: mido
language: kr
timezone: Asia/Seoul

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: midojeong.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

#Custom Setting Start

# Site settings
SEOTitle: mido
email: minidonut03@gmail.com
description: mido's IT blog github page
keyword: ""
header-img: img/header_img/home-bg-2-dark.jpg
signature: false #show signature
signature-img: img/signature/BeanTechSign-white.png 


# SNS settings
# RSS: false
# weibo_username:     Demonbaneen
# zhihu_username:     Demonbane
github_username:    midojeong
# twitter_username:   Demonbane_x
# facebook_username:  Demonbane
# linkedin_username:  Demonbane

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings
disqus_username: midojeong

# Analytics settings
# Baidu Analytics
# ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics

ga_track_id: 'UA-116376595-1'          # Format: UA-xxxxxx-xx
ga_domain: https://midojeong.github.io


# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "Functional Programming / JavaScript / Haskell / Front-end / Design / UX / UI / ..."
sidebar-about-contact: "minidonut03@gmail.com,"
sidebar-about-check: "check on every 19:00"
sidebar-avatar: img/ironman-draw.png      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
# - featured-tags
- short-about
# - recent-posts
# - friends-blog
# - archive
# - category

# widget behavior
## Archive
archive_type: 'monthly'
show_count: true


## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


## Friends
# friends: [
#     {
#         title: "Bean Tech",
#         href: "http://beantech.org"
#     },{
#         title: "Kaijun's Blog",
#         href: "http://blog.kaijun.rocks"
#     },{
#         title: "Hux Blog",
#         href: "http://huangxuan.me"
#     },{
#         title: "It Helps SEO",
#         href: "#"
#     }
# ]


#Custom Setting End



# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  
# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'
  plugins:
    - markdown-it-abbr
    - markdown-it-footnote
    - markdown-it-ins
    - markdown-it-sub
    - markdown-it-sup
  
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: beantech

#sitemap
sitemap:
  path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/midojeong/midojeong.github.io
  branch: master
